spring:
  datasource:
    username : root
    password :
    url: jdbc:mysql://10.130.44.108:3306/cmdb
    driver-class-name : com.mysql.jdbc.Driver

mybatis:
  mapper-locations : classpath:mapper/*Mapper.xml
  type-aliases-package : com.example.entity

ccod:
  ccod-kernel-module:
    Glsserver:
      alias : gls
    LicenseServer:
      alias : license
    DDSServer:
      alias : dds
    cmsserver:
      alias : cms
    ucxserver:
      alias : ucx
    DataKeeper:
      alias : datakeeper
    RMServer:
      alias : rm
    UCDServer:
      alias : ucds
    dcs:
      alias : dcs
    StatSchedule:
      alias : ss
    EAService:
      alias : eas
    dae:
      alias : dae
    psr:
      alias : psr
    fpsvr:
      alias : fps
    dcproxy:
      alias : dcproxy
    daengine:
      alias : daengine
    tsrecadsrv:
      alias : tsr
    tsr-longlink:
      alias : tsrl
    AgentProxy:
      alias : agentproxy

nexus:
  user : admin
  password : 123456
  host-url : http://10.130.41.216:8081
  app-module-repository : ccod_modules
  platform-app-cfg-repository : platform_app_cfg

app-publish-nexus:
  user: admin
  password: 123456
  host-url: http://10.130.41.216:8081

activemq:
  brokerUrl : failover:(tcp://10.130.44.108:61616)?timeout=3000
  receive-time-span: 300

cmdb:
  server-name: support_dev_cmdb_server3
  share-secret: ae12139afadabde12345r
  app-collect:
    receipt-timeout: 500000
    collect-data-timeout: 28800000
    transfer-file-timeout: 28800000
    start-data-collect-instruction: START_APP_DATA_COLLECT
    start-file-transfer-instruction: START_APP_FILE_TRANSFER
    app-file-attribute-key: FILE_ATTRIBUTE

lj-paas:
  excludes:
    - 蓝鲸
    - 配置管理
    - Oracle切换_qn
    - Oracle切换_tool
    - test1
  host-url: http://paas.ccod.com:80
  bk-app-code: wyffirstsaas
  bk-app-secret: 8a4c0887-ca15-462b-8804-8bedefe1f352
  user-name: admin
  idle-pool-set-name: idle pool
  idle-pool-set-id: ccodIdlePool
  update-schema-set-name: 平台升级方案
  update-schema-set-id: platformUpdateSchema
  set-apps:
    set[0]:
      name: 域服务
      id: domainService
      isBasic: 1
      fixedDomainName:
      fixedDomainId:
      apps:
        - cmsserver
        - daengine
        - DataKeeper
        - dcproxy
        - dcs
        - ddaengine
        - ddcs
        - DDSServer
        - tsrecadsrv
        - tsr2
        - UCDServer
        - ucxserver
        - EAService
        - fpsvr
        - psr
        - slee
        - StatSchedule
    set[1]:
      name: 公共组件
      id: publicModules
      isBasic: 1
      fixedDomainName: 相关模块
      fixedDomainId: modules
      apps:
        - LicenseServer
    set[2]:
      name: 网关接入
      id: gatewayAccess
      isBasic: 1
      fixedDomainName: 网关
      fixedDomainId: gateway
      apps:
        - umg
    set[3]:
      name: 管理门户
      id: managerPortal
      isBasic: 1
      fixedDomainName: 门户
      fixedDomainId: portal
      apps:
        - agentProxy
        - cci2
        - customWebservice
        - dcms;dcmsDialer
        - dcmsDialerWebservice
        - dcmsMonitor
        - dcmsNEWSG
        - dcmsRecord
        - dcmsRecordCXM
        - dcmssg;dcmsSG
        - dcmsSR
        - dcmsStatics
        - dcmsStaticsIB
        - dcmsStaticsReport
        - dcmsStaticsReportfj
        - dcmsStaticsReportNew
        - dcmsWebservice
        - dcmsWebservicespeed
        - dcmsWebservicespeednew
        - dcmsWebserviceucds
        - dcmsx
        - httpd
        - IBcustomWebservice
        - IBsafetymonitor
        - interfaceAdapter
        - ivrprocessinterface
        - omsp;PADnStatistics
        - PADnStatisticsbilibili
        - PAreload
        - portal
        - safetyMonitor
        - safetyStatics
        - safetyStaticsQT
        - tomcat
    set[4]:
      name: 对外接口
      id: api
      isBasic: 1
      fixedDomainName: 接口
      fixedDomainId: interface
      apps:
    set[5]:
      name: 运营门户
      id: supportPortal
      isBasic: 1
      fixedDomainName: 门户
      fixedDomainId: portal
      apps:
        - glsServer
        - httpd
        - IBcustomWebs
        - IBsafetymoni
        - licen
    set[6]:
      name: 外拨模块
      id: apgModules
      isBasic: 0
      fixedDomainName: 外拨域
      fixedDomainId: apgDomain
      apps:
        - AppGateWay
        - DialEngine
        - UCGateway

windows: false

debug: false

develop: true