spring:
  datasource:
    username : root
    password : qnsoft
    url: jdbc:mysql://10.130.76.80:3306/cmdb_new
    driver-class-name : com.mysql.jdbc.Driver

mybatis:
  mapper-locations : classpath:mapper/*Mapper.xml
  type-aliases-package : com.example.entity

ccod:
  domain-id-regex: ^[0-9a-z][0-9a-z\\-]*[0-9a-z]$
  app-standard-alias-regex: ^[a-z]+[0-9a-z\\-]*[a-z0-9]$
  notCheckCfgApps:
    - cmsserver
  platform-deploy-template: platform_deploy.py

nexus:
  user : admin
  password : 123456
  host-url : http://10.130.41.216:8081
  app-module-repository : ccod_modules
  platform-app-cfg-repository : platform_app_cfg
  tmp-platform-app-cfg-repository: tmp
  platform-deploy-script-repository: some_test
  nexus-docker-url: nexus.io:5000
  image-repository: ccod

git:
  k8s_deploy_git_url: http://10.130.24.101/wuph/payaml.git


app-publish-nexus:
  user: admin
  password: 123456
  host-url: http://10.130.41.216:8081

activemq:
  brokerUrl : failover:(tcp://119.57.255.4:61616)?timeout=3000
  receive-time-span: 300

cmdb:
  url: http://10.130.41.218:8086/cmdb
  server-name: support_dev_cmdb_server3
  share-secret: ae12139afadabde12345r
  app-collect:
    receipt-timeout: 10000
    collect-data-timeout: 28800000
    transfer-file-timeout: 28800000
    start-data-collect-instruction: START_APP_DATA_COLLECT
    start-file-transfer-instruction: START_APP_FILE_TRANSFER
    app-file-attribute-key: FILE_ATTRIBUTE

lj-paas:
  excludes:
    - 蓝鲸
    - 配置管理
    - Oracle切换_qn
    - Oracle切换_tool
    - test1
  host-url: http://paas.ccod.com:80
  bk-app-code: wyffirstsaas
  bk-app-secret: 8a4c0887-ca15-462b-8804-8bedefe1f352
  user-name: admin
  idle-pool-set-name: idle pool
  idle-pool-set-id: ccodIdlePool
  update-schema-set-name: 平台升级方案
  update-schema-set-id: platformUpdateSchema
  host-default-cloud-id: 5
  set-apps:
    set[0]:
      name: 公共组件
      id: publicModules
      isBasic: 1
      fixedDomainName: 相关模块
      fixedDomainId: public
      domainType: 2
      apps:
        - LicenseServer/licenseserver
        - configserver/configserver
        - glsServer/glsserver:30
        - RMServer
    set[1]:
      name: 网关接入
      id: gatewayAccess
      isBasic: 1
      fixedDomainName: 网关
      fixedDomainId: gateway
      domainType: 3
      apps:
        - umg
    set[2]:
      name: 域服务
      id: domainService
      isBasic: 1
      fixedDomainName: 服务域
      fixedDomainId: cloud
      domainType: 1
      apps:
        - DDSServer/dds:20
        - UCDServer/ucds:20
        - dcs/dcs:20
        - cmsserver/cms:20
        - ucxserver/ucx:20
        - daengine/daengine:20
        - DataKeeper
        - dcproxy/dcproxy
        - ddaengine
        - ddcs
        - tsrecadsrv
        - tsr2
        - EAService
        - fpsvr
        - psr
        - slee
        - StatSchedule/ss
    set[3]:
      name: 管理门户
      id: managerPortal
      isBasic: 1
      fixedDomainName: 管理门户域
      fixedDomainId: manage
      domainType: 4
      apps:
        - agentProxy
        - cas/cas
        - cci2
        - customWebservice/customwebservice
        - dcms/dcms
        - dcmsDialer
        - dcmsDialerWebservice
        - dcmsMonitor
        - dcmsNEWSG
        - dcmsRecord/dcmsrecord
        - dcmsRecordCXM
        - dcmssg/dcmssg
        - dcmsSG
        - dcmsSR
        - dcmsStatics/dcmsstatics
        - dcmsStaticsIB
        - dcmsStaticsReport/dcmsstaticsreport
        - dcmsStaticsReportfj
        - dcmsStaticsReportNew
        - dcmsWebservice/dcmswebservice
        - dcmsWebservicespeed
        - dcmsWebservicespeednew
        - dcmsWebserviceucds
        - dcmsx/dcmsx
        - httpd
        - IBcustomWebservice
        - IBsafetymonitor
        - interfaceAdapter
        - ivrprocessinterface
        - omsp
        - PADnStatistics
        - PADnStatisticsbilibili
        - PAreload
        - portal
        - safetyMonitor/safetymonitor
        - safetyStatics
        - safetyStaticsQT
        - tomcat
    set[4]:
      name: 对外接口
      id: api
      isBasic: 1
      fixedDomainName: 接口
      fixedDomainId: api
      domainType: 5
      apps:
    set[5]:
      name: 运营门户
      id: supportPortal
      isBasic: 1
      fixedDomainName: 运营门户域
      fixedDomainId: ops
      domainType: 6
      apps:
        - gls/gls
        - httpd
        - IBcustomWebs
        - IBsafetymoni
        - licen
    set[6]:
      name: 外拨模块
      id: apgModules
      isBasic: 0
      fixedDomainName: 外拨域
      fixedDomainId: apg-domain
      domainType: 7
      apps:
        - AppGateWay
        - DialEngine
        - UCGateway

k8s:
  gls_oracle_svc_name: oracle
  gls_oracle_sid: xe


windows: false

debug: false

develop: true

test:
  new-create-biz-id: 12
  demo-new-create-platform-id: ccodDevelopTestPlatform
  demo-new-create-platform-name: ccod开发测试平台
  demo-update-platform-id: updateDemoPlatform