spring:
  datasource:
    username : root
    password :
    url: jdbc:mysql://10.130.44.108:3306/cmdb
    driver-class-name : com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations : classpath:mapper/*Mapper.xml
  type-aliases-package : com.example.entity

ccod:
  ccod_kernel_module:
    default_base_path : /home/ccodrunner/Platform
    default_bin : ./bin/{module_alias_name}
    default_cfg_path : ./cfg
    default_log_path : ./log
    default_version_control : git
    default_run_method : runnable
    nexus_repository : CCOD
    nexus_package_name: modules/{module_name}/{version}/{module_alias}
    nexus_cfg_name: modules/{module_name}/{version}/cfg/{cfg_filename}
    nexus_note_name: modules/{module_name}/{version}/note/note.txt
    Glsserver:
      alias : gls
      bin : ./bin/glsserver.jar
      log_path : ./log
      version_control : git
      runnable : jar_runnable
    LicenseServer:
      alias : license
    DDSServer:
      alias : dds
    cmsserver:
      alias : cms
    ucxserver:
      alias : ucx
    DataKeeper:
      alias : datakeeper
    RMServer:
      alias : rm
    UCDServer:
      alias : ucds
    dcs:
      alias : dcs
    StatSchedule:
      alias : ss
    EAService:
      alias : eas
    dae:
      alias : dae
    psr:
      alias : psr
    fpsvr:
      alias : fps
    dcproxy:
      alias : dcproxy
    daengine:
      alias : daengine
    tsrecadsrv:
      alias : tsr
    tsr_longlink:
      alias : tsrl
    AgentProxy:
      alias : agentproxy

nexus:
  user : admin
  password : 123456
  host_url : http://10.130.41.216:8081
  app_module_repository : ccod_modules
  platform_app_cfg_repository : platform_app_cfgs
  query_asset_url : ${nexus_host}/service/rest/v1/assets/{asset_id}
  upload_raw_url : ${nexus_host}/service/rest/v1/components?repository=%s

activemq:
  brokerUrl : failover:(tcp://10.130.44.108:61616)?timeout=3000
  receive_time_span: 300

cmdb:
  server_name: support_dev_cmdb_server
  share_secret: ae12139afadabde12345r
  app_collect:
    receipt_timeout: 5000
    collect_data_timeout: 7200000
    transfer_file_timeout: 7200000
    start_data_collect_instruction: START_APP_DATA_COLLECT
    start_file_transfer_instruction: START_APP_DATA_TRANSFER
    client_receipt_topic: RECEIPT_OF_{platformId}_TO_CMDB
    file_type: FILE.TYPE
    install_package: INSTALLPACKAGE
    cfg: CFG
    app_name: APP.NAME
    app_alias: APP.ALIAS
    app_version: APP.VERSION
    platformId: PLATFORMID
    domainName: DOMAINNAME
    host_ip: HOSTIP
    base_path: BASEPATH
    deploy_path: DEPLOYPATH
    file_name: FILENAME
    file_size: FILESIZE
    file_md5: FILEMD5




