spring:
  datasource:
    username : root
    password : qnsoft
    url: jdbc:mysql://10.130.76.80:3306/cmdb_api
    driver-class-name : com.mysql.jdbc.Driver

mybatis:
  mapper-locations : classpath:mapper/*Mapper.xml
  type-aliases-package : com.example.entity

ccod:
  domain-id-regex: ^[0-9a-z][0-9a-z\\-]*[0-9a-z]$
  app-standard-alias-regex: ^[a-z]+[0-9a-z\\-]*[a-z0-9]$
  notCheckCfgApps:
    - cmsserver
  platform-deploy-template: platform_deploy.py
  set[0]:
    name: 公共组件
    id: publicModules
    isBasic: 1
    fixedDomainName: 公共组件
    fixedDomainId: public
    apps[0]:
      name: LicenseServer
      alias: licenseserver
    apps[1]:
      name: configserver
      alias: configserver
    apps[2]:
      name: glsServer
      alias: glsserver
      delay: 30
    apps[3]:
      name: RMServer
  set[1]:
    name: 网关接入
    id: gatewayAccess
    isBasic: 1
    fixedDomainName: 网关
    fixedDomainId: gateway
    apps[0]:
      name: umg
  set[2]:
    name: 域服务
    id: domainService
    isBasic: 1
    fixedDomainName: 服务域
    fixedDomainId: cloud
    apps[0]:
      name: DDSServer
      alias: dds
      delay: 20
    apps[1]:
      name: UCDServer
      alias: ucds
      delay: 20
    apps[2]:
      name: dcs
      alias: dcs
      delay: 20
    apps[3]:
      name: cmsserver
      alias: cms
      delay: 20
    apps[4]:
      name: ucxserver
      alias: ucx
      delay: 20
    apps[5]:
      name: daengine
      alias: daengine
      delay: 20
    apps[6]:
      name: DataKeeper
    apps[7]:
      name: dcproxy
      alias: dcproxy
      delay: 20
    apps[8]:
      name: ddaengine
    apps[9]:
      name: ddcs
      alias: ddcs
      delay: 20
    apps[10]:
      name: tsrecadsrv
    apps[11]:
      name: tsr2
    apps[12]:
      name: EAService
    apps[13]:
      name: fpsvr
    apps[14]:
      name: psr
    apps[15]:
      name: slee
    apps[16]:
      name: StatSchedule
      alias: ss
  set[3]:
    name: 管理门户
    id: managerPortal
    isBasic: 1
    fixedDomainName: 管理门户域
    fixedDomainId: manage
    apps[0]:
      name: agentProxy
    apps[1]:
      name: cas
    apps[2]:
      name: cci2
    apps[3]:
      name: customWebservice
      alias: customwebservice
    apps[4]:
      name: dcms
      alias: dcms
    apps[5]:
      name: dcmsDialer
    apps[6]:
      name: dcmsDialerWebservice
    apps[7]:
      name: dcmsMonitor
    apps[8]:
      name: dcmsNEWSG
    apps[9]:
      name: dcmsRecord
      alias: dcmsrecord
    apps[10]:
      name: dcmsRecordCXM
    apps[11]:
      name: dcmssg
      alias: dcmssg
    apps[12]:
      name: dcmsSG
      alias: dcmssg2
    apps[13]:
      name: dcmsSR
    apps[14]:
      name: dcmsStatics
      alias: dcmsstatics
    apps[15]:
      name: dcmsStaticsIB
    apps[16]:
      name: dcmsStaticsReport
      alias: dcmsstaticsreport
    apps[17]:
      name: dcmsStaticsReportfj
    apps[18]:
      name: dcmsStaticsReportNew
    apps[19]:
      name: dcmsWebservice
      alias: dcmswebservice
    apps[20]:
      name: dcmsWebservicespeed
    apps[21]:
      name: dcmsWebservicespeednew
    apps[22]:
      name: dcmsWebserviceucds
    apps[23]:
      name: dcmsx
      alias: dcmsx
    apps[24]:
      name: httpd
    apps[25]:
      name: IBcustomWebservice
    apps[26]:
      name: IBsafetymonitor
    apps[27]:
      name: interfaceAdapter
    apps[28]:
      name: ivrprocessinterface
    apps[29]:
      name: omsp
    apps[30]:
      name: PADnStatistics
    apps[31]:
      name: PADnStatisticsbilibili
    apps[32]:
      name: PAreload
    apps[33]:
      name: portal
    apps[34]:
      name: safetyMonitor
      alias: safetymonitor
    apps[35]:
      name: safetyStatics
    apps[36]:
      name: safetyStaticsQT
    apps[37]:
      name: tomcat
  set[4]:
    name: 对外接口
    id: api
    isBasic: 1
    fixedDomainName: 接口
    fixedDomainId: api
    apps:
  set[5]:
    name: 运营门户
    id: supportPortal
    isBasic: 1
    fixedDomainName: 运营门户域
    fixedDomainId: ops
    apps[0]:
      name: gls
      alias: gls
    apps[1]:
      name: httpd
    apps[2]:
      name: IBcustomWebs
    apps[3]:
      name: IBsafetymoni
    apps[4]:
      name: licen
  set[6]:
    name: 外拨模块
    id: apgModules
    isBasic: 0
    fixedDomainName: 外拨域
    fixedDomainId: apg-domain
    apps[0]:
      name: AppGateWay
    apps[1]:
      name: DialEngine
    apps[2]:
      name: UCGateway

  threePartApps:
    - oracle
    - mysql
  threePartServices:
    - umg

nexus:
  user : admin
  password : 123456
  host-url : http://10.130.41.218:8081
  app-module-repository : ccod_module_releases
  platform-app-cfg-repository : platform_app_cfg
  unconfirmed-platform-app-repository: unconfirmed-platform-app
  tmp-platform-app-cfg-repository: tmp
  platform-deploy-script-repository: some_test
  nexus-docker-url: nexus.io:5000
  image-repository: ccod

git:
  k8s_deploy_git_url: http://10.130.24.101/wuph/payaml.git


app-publish-nexus:
  user: admin
  password: 123456
  host-url: http://10.130.41.218:8081

activemq:
  brokerUrl : failover:(tcp://119.57.255.4:61616)?timeout=3000
  receive-time-span: 300

cmdb:
  url: http://10.130.41.218:8086/cmdb
  server-name: support_dev_cmdb_server4
  share-secret: ae12139afadabde12345r
  app-collect:
    receipt-timeout: 10000
    collect-data-timeout: 28800000
    transfer-file-timeout: 28800000
    start-data-collect-instruction: START_APP_DATA_COLLECT
    start-file-transfer-instruction: START_APP_FILE_TRANSFER
    app-file-attribute-key: FILE_ATTRIBUTE

onlinemanager:
  master:
    id: qntool

lj-paas:
  excludes:
    - 蓝鲸
    - 配置管理
    - Oracle切换_qn
    - Oracle切换_tool
    - test1
  host-url: http://paas.ccod.com:80
  bk-app-code: wyffirstsaas
  bk-app-secret: 8a4c0887-ca15-462b-8804-8bedefe1f352
  user-name: admin
  idle-pool-set-name: idle pool
  idle-pool-set-id: ccodIdlePool
  update-schema-set-name: 平台升级方案
  update-schema-set-id: platformUpdateSchema
  host-default-cloud-id: 5


image:
  nexusUrl: nexus.io:5000
  nexusUser: admain
  nexusPwd: 123456
  ccodModuleRepository:
    - ccod
  threeAppRepository:
    - db

k8s:
  gls_oracle_svc_name: oracle
  gls_oracle_sid: xe
  labels:
    domain-id: domain-id
    app-name: app-name
    app-alias: alias
    app-version: version
    app-type: app-type
    job-id: job-id
    service-type: service-type
    deployment-tag: assemble-tag
    deployment-type: type
  volume-names:
    web-app: war
    binary-file: binary-file
  deployment:
    defaultCfgMountPath: /cfg


windows: false

debug: false

develop: true

test:
  new-create-biz-id: 12
  demo-new-create-platform-id: ccodDevelopTestPlatform
  demo-new-create-platform-name: ccod开发测试平台
  demo-update-platform-id: updateDemoPlatform