spring:
  datasource:
    username : root
    password :
    url: jdbc:mysql://10.130.44.108:3306/cmdb
    driver-class-name : com.mysql.jdbc.Driver

mybatis:
  mapper-locations : classpath:mapper/*Mapper.xml
  type-aliases-package : com.example.entity

ccod:
  ccod_kernel_module:
    default_base_path : /home/ccodrunner/Platform
    default_bin : ./bin/{module_alias_name}
    default_cfg_path : ./cfg
    default_log_path : ./log
    default_version_control : git
    default_run_method : runnable
    nexus_repository : CCOD
    nexus_package_name: modules/{module_name}/{version}/{module_alias}
    nexus_cfg_name: modules/{module_name}/{version}/cfg/{cfg_filename}
    nexus_note_name: modules/{module_name}/{version}/note/note.txt
    Glsserver:
      alias : gls
      bin : ./bin/glsserver.jar
      log_path : ./log
      version_control : git
      runnable : jar_runnable
    LicenseServer:
      alias : license
    DDSServer:
      alias : dds
    cmsserver:
      alias : cms
    ucxserver:
      alias : ucx
    DataKeeper:
      alias : datakeeper
    RMServer:
      alias : rm
    UCDServer:
      alias : ucds
    dcs:
      alias : dcs
    StatSchedule:
      alias : ss
    EAService:
      alias : eas
    dae:
      alias : dae
    psr:
      alias : psr
    fpsvr:
      alias : fps
    dcproxy:
      alias : dcproxy
    daengine:
      alias : daengine
    tsrecadsrv:
      alias : tsr
    tsr_longlink:
      alias : tsrl
    AgentProxy:
      alias : agentproxy

nexus:
  user : admin
  password : 123456
  host_url : http://10.130.41.216:8081
  app_module_repository : ccod_modules
  platform_app_cfg_repository : platform_app_cfg

app_publish_nexus:
  user: admin
  password: 123456
  host_url: http://10.130.41.216:8081

activemq:
  brokerUrl : failover:(tcp://10.130.44.108:61616)?timeout=3000
  receive_time_span: 300

cmdb:
  server_name: support_dev_cmdb_server3
  share_secret: ae12139afadabde12345r
  app_collect:
    receipt_timeout: 500000
    collect_data_timeout: 28800000
    transfer_file_timeout: 28800000
    start_data_collect_instruction: START_APP_DATA_COLLECT
    start_file_transfer_instruction: START_APP_FILE_TRANSFER
    app_file_attribute_key: FILE_ATTRIBUTE

lj_paas:
  exclude_biz: 2;4;5;6;8
  host_url: http://paas.ccod.com:80
  bk_app_code: wyffirstsaas
  bk_app_secret: 8a4c0887-ca15-462b-8804-8bedefe1f352
  user_name: admin
  idle_pool_set_name: idle pools
  set_module : 域服务:cmsserver;daengine;DataKeeper;dcproxy;dcs;ddaengine;ddcs;DDSServer;tsrecadsrv;tsr2;UCDServer;ucxserver;EAService;fpsvr;psr;slee;StatSchedule;DialEngine|公共组件@PblicModules:LicenseServer|网关接入@Gateway:umg;UCGateway;AppGateWay|管理门户@ManagerPortal:agentProxy;cci2;customWebservice;dcms;dcmsDialer;dcmsDialerWebservice;dcmsMonitor;dcmsNEWSG;dcmsRecord;dcmsRecordCXM;dcmssg;dcmsSG;dcmsSR;dcmsStatics;dcmsStaticsIB;dcmsStaticsReport;dcmsStaticsReportfj;dcmsStaticsReportNew;dcmsWebservice;dcmsWebservicespeed;dcmsWebservicespeednew;dcmsWebserviceucds;dcmsx;glsServer;httpd;IBcustomWebservice;IBsafetymonitor;interfaceAdapter;ivrprocessinterface;omsp;PADnStatistics;PADnStatisticsbilibili;PAreload;portal;safetyMonitor;safetyStatics;safetyStaticsQT;tomcat|对外接口@Interface|运营门户@SupportPortal:gls|httpd|IBcustomWebs|IBsafetymoni|licen


windows: false

debug: false

develop: true