jdk7: /opt/jdk1.7.0_79
jdk8: /opt/jdk1.8.0_131
resin4: /opt/resin
tomcat6: /opt/tomcat
skip-apps:
  - gls
  - dcms
nginx:
  conf: /etc/nginx/conf.d/default.conf
  listen:
    http: 80
    https: 443 ssl
  proxy-set-header:
    - Host $host
    - X-Real-IP $remote_addr
    - X-Forwarded-For $proxy_add_x_forwarded_for